### ISSUE TITLE
genType support

### ISSUE THREAD

**Issue by sgrove** [zth/pgtyped-rescript#3]
There are a few low-hanging bits of fruit that would enable a first-pass at genType support!

As an example of the changes necessary, here is are the manual tweaks I made to the pgtyped-rescript artifacts  https://gist.github.com/sgrove/68c85bd81f3776bfa4bf9ad9baf1bb48/revisions

1. type aliases with `@genType.opaque` to hide the upstream types (`pgClient`, `Null.t`) + manual type specification for the parameters https://github.com/rescript-association/genType/issues/636 and https://github.com/rescript-association/genType/issues/634#issuecomment-1681551617
2. No labeled arguments, since genType just outputs the wrong stuff https://github.com/rescript-association/genType/issues/635

With those changes, we get this behavior in TypeScript:
<img width="769" alt="Screenshot 2023-08-16 at 21 12 10" src="https://github.com/zth/pgtyped-rescript/assets/35296/058927ae-c38e-417e-bebf-e2e3bced2c90">

It doesn't provide an all-the-way optimal experience on the other side (e.g. pgClient isn't appropriately typed):
<img width="754" alt="Screenshot 2023-08-16 at 21 12 23" src="https://github.com/zth/pgtyped-rescript/assets/35296/a9e4990d-ad6f-4e72-b502-dec8110045f0">

But it's a minor detail compared to the experience before!

**Comment by zth** [comment]
Closed in https://github.com/adelsz/pgtyped/commit/fa3672f5ea97dc1155003439b6bd9fb42a646dd3 (please try it)
