### ISSUE TITLE
Convenience methods

### ISSUE THREAD

**Issue by sgoai** [zth/pgtyped-rescript#4]
It'd be nice to generate variations of every function:

e.g.

```sql
/* @name findDataSetCaseById */
SELECT * FROM test_case where id = :id! limit 1;
```

could generate:

- `findDataSetCaseById`- a list of results
- `findDataSetCaseByIdOne` - a single result, throws an exception if there isn't exactly one element
-`findDataSetCaseByIdOneOpt` - a single `option` of a result

**Comment by zth** [comment]
Closed in https://github.com/adelsz/pgtyped/commit/087010835eb712fec2b5d117348ef65e0c2c2175
