### ISSUE TITLE
Querying for an array of jsonb generates invalid rescript

### ISSUE THREAD

**Issue by sgoai** [zth/pgtyped-rescript#5]
**Describe the bug**
Selecting a column of type `jsonb[]` will generate invalid rescript:

```
/* @name findById */
SELECT examples FROM test_case where id = :id! limit 1;
```

generates:

```
open PgTyped
type Js.Json.tArray = array<Js.Json.t>

/** 'FindById' parameters type */
type findByIdParams = {
  id: string,
}

/** 'FindById' return type */
type findByIdResult = {
  /** Examples conforming to the input schema */
  examples: Null.t<Js.Json.tArray>,
}
```

`type Js.Json.tArray` is syntactically invalid

**Expected behavior**
The type value is fine, so maybe just munging `Js.Json.tArray` to `jsJsontArray` would be enough?

**Comment by zth** [comment]
Closed in https://github.com/adelsz/pgtyped/commit/50adfad45748f36b1c7e9c89caf4d221b554a5ed
